### PR TITLE
fix bad computing qAtNominalV and maxSusceptance values

### PR DESCRIPTION
**Pull request by ghazwarhili**

### CODE REVIEW

**Comment by basseche** [comment]
This fix introduce a new bug :

Capture d’écran du 2024-10-29 13-48-12
 
- if i modifiy sections number from 1 to 3, using regular modification or modification by formula :
Capture d’écran du 2024-10-29 13-49-02

- the value of QMax available at nominal voltage is divied by 3. It should not change !

**Review by basseche — CHANGES_REQUESTED** [review]
This fix introduce a new bug please see comment.

**Comment by ghazwarhili** [comment]
it is normal behaivor !
QMax available at nominal voltage is changed because the susceptance has changed the value

**Comment by basseche** [comment]
> it is normal behaivor ! QMax available at nominal voltage is changed because the susceptance has changed the value

No it's not. Changing number of sections should not change suceptance and by the same time QMax.

**Pull request closed without merging**
