### PR TITLE
Fix get values of positions infos when creating from copy

### PR DESCRIPTION
**Pull request by bendaamerahm**

### CODE REVIEW

**Review by FranckLecuyer — CHANGES_REQUESTED** [review]
Add tests with ConnectablePosition extension set on equipment, in order to have non null values for connectionName and connectionDirection fields ...

**Review by archendel — COMMENTED** [review]
All test resources have connectionName / connectionDirection set to "null", should we create a test with those attributes not defined to null ?

**Review by archendel — CHANGES_REQUESTED** [review]
When I try to create a load from copy, connectionName and connectionDirection are always set to null even if they weren't null in the original load

**Review by FranckLecuyer — CHANGES_REQUESTED** [review]
Front GridStudy must be changed to set the new connection direction and the new connection name fields provided by this PR (inside the 'toFormValues' functions in the different creation dialogs)

**Review by FranckLecuyer — APPROVED** [review]

**Review by archendel — APPROVED** [review]

**Pull request merged**
